name: "Publish Devcontainer Features"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 13 * * 6"
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  publish-features:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Publish cargo-near"
        uses: devcontainers-community/publish-feature@v1
        with:
          path: ".devcontainer/cargo-near"
          image: "ghcr.io/near/near-devcontainers/features/cargo-near"

      - name: "Publish near-cli"
        uses: devcontainers-community/publish-feature@v1
        with:
          path: ".devcontainer/near-cli"
          image: "ghcr.io/near/near-devcontainers/features/near-cli"
